### ISSUE TITLE
Mise en place commentaire

### ISSUE THREAD

**Issue by guichou21** [gbesset/java-gbc-wall#8]
Mise en place Commentaire sur un Item
- recuperation des commentaires pour un item donné (get Item)
- nb de commentaire pour un item donné
- modif/suppression commentaires

**Comment by gbesset** [comment]
reste :
- service
- controller
- outil migration v1 - v2

**Comment by gbesset** [comment]
PB boolean false à tous les commentaires ...
Pb infinite loop a cause lazy hibernate -> palié par JsonIgnore
du coup plus de item_id dans comment.....
passer paDTO?
https://desgeeksetdeslettres.com/programmation-java/spring-et-jackson-filtrer-les-donnees-pour-eviter-les-lazyloadingexception

https://desgeeksetdeslettres.com/programmation-java/dozer-a-la-rescousse-du-lazy-loading

http://www.baeldung.com/jackson
